/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>'],
  testMatch: ['**/tests/**/*.test.ts'],
  testPathIgnorePatterns: [
    '<rootDir>/tests/unit/visualizers/ThreeJsRenderer.test.ts',
    '<rootDir>/tests/integration/formatConversion.integration.test.ts',
  ],
  moduleNameMapper: {
    '^vscode$': '<rootDir>/tests/mocks/vscode.ts',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/test/**',
    '!src/**/index.ts',
    '!src/parsers/**',
    '!src/providers/lsp/**',
    '!src/server.ts',
    '!src/**/index.ts',
    '!src/features/**',
    '!src/data/**',
    '!src/extension.ts',
    '!src/managers/LSPManager.ts',
    '!src/providers/DataPlotter.ts',
    '!src/providers/StructureViewer.ts',
    '!src/visualizers/MoleculeViewerPanel.ts',
    '!src/visualizers/ThreeJsRenderer.ts',
    '!src/visualizers/ThreeJsWebview.ts',
    '!src/commands/**',
    '!src/visualizers/types.ts',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'text-summary', 'lcov', 'html'],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 95,
      lines: 90,
      statements: 90,
    },
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
};
