/**
 * KPOINTS Migration Utilities
 */

export interface KpointGrid {
  grid: [number, number, number];
  type: 'Gamma-centered' | 'Monkhorst-Pack';
  shift: [number, number, number];
  comment?: string;
}

export function parseVASP_KPOINTS(content: string): KpointGrid {
  const lines = content
    .trim()
    .split('\n')
    .map(l => l.trim())
    .filter(l => l);

  if (lines.length < 4) {
    throw new Error('Invalid VASP KPOINTS format');
  }

  const comment = lines[0];
  const scheme = lines[2]?.toLowerCase() || 'gamma';
  const grid = lines[3]?.split(/\s+/).map(Number) || [4, 4, 4];
  const shift = lines[4]?.split(/\s+/).map(Number) || [0, 0, 0];

  return {
    grid: [grid[0], grid[1], grid[2]],
    type: scheme.includes('gamma') ? 'Gamma-centered' : 'Monkhorst-Pack',
    shift: [shift[0] || 0, shift[1] || 0, shift[2] || 0],
    comment,
  };
}

export function generateVASP_KPOINTS(grid: KpointGrid): string {
  const lines = [grid.comment || 'Generated by OpenQC', '0'];
  lines.push(grid.type === 'Gamma-centered' ? 'Gamma' : 'Monkhorst-Pack');
  lines.push(`${grid.grid[0]} ${grid.grid[1]} ${grid.grid[2]}`);
  lines.push(`${grid.shift[0]} ${grid.shift[1]} ${grid.shift[2]}`);
  return lines.join('\n');
}

export function parseQE_KPOINTS(content: string): KpointGrid {
  const lines = content
    .trim()
    .split('\n')
    .filter(l => l);
  const firstLine = lines[0]?.toLowerCase() || '';

  if (firstLine.includes('gamma')) {
    return {
      grid: [1, 1, 1],
      type: 'Gamma-centered',
      shift: [0, 0, 0],
    };
  }

  const gridLine = lines[1]?.split(/\s+/).map(Number) || [4, 4, 4];
  const shiftLine = lines[2]?.split(/\s+/).map(Number) || [0, 0, 0];

  return {
    grid: [gridLine[0], gridLine[1], gridLine[2]],
    type: 'Monkhorst-Pack',
    shift: [shiftLine[0] || 0, shiftLine[1] || 0, shiftLine[2] || 0],
  };
}

export function generateQE_KPOINTS(grid: KpointGrid): string {
  return [
    'K_POINTS AUTOMATIC',
    `${grid.grid[0]} ${grid.grid[1]} ${grid.grid[2]}`,
    `${grid.shift[0]} ${grid.shift[1]} ${grid.shift[2]}`,
  ].join('\n');
}

export function monkhorstToGamma(grid: [number, number, number]): [number, number, number] {
  return grid.map(g => g * 2) as [number, number, number];
}

export function gammaToMonkhorst(grid: [number, number, number]): [number, number, number] {
  return grid.map(g => g / 2) as [number, number, number];
}

export function detectKpointFormat(content: string): 'vasp' | 'qe' | 'unknown' {
  const firstLine = content.trim().split('\n')[0]?.toLowerCase() || '';
  if (firstLine.includes('k_points')) return 'qe';
  if (content.trim().split('\n')[1]?.trim() === '0') return 'vasp';
  return 'unknown';
}

export function parseKpoints(content: string): KpointGrid {
  const format = detectKpointFormat(content);
  return format === 'qe' ? parseQE_KPOINTS(content) : parseVASP_KPOINTS(content);
}

export function generateKpoints(grid: KpointGrid, format: 'vasp' | 'qe'): string {
  return format === 'qe' ? generateQE_KPOINTS(grid) : generateVASP_KPOINTS(grid);
}

export class KpointMigration {
  constructor(private _context: any) {}

  isSupported(source: string, target: string): boolean {
    const supported = ['vasp', 'qe'];
    return supported.includes(source) && supported.includes(target);
  }

  static migrate(content: string, targetFormat: 'vasp' | 'qe'): string {
    return generateKpoints(parseKpoints(content), targetFormat);
  }
}

// For migrationCommands.ts compatibility - supports both signatures
export function quickMigrateKpoints(
  contextOrContent: any,
  contentOrTarget?: string,
  targetFormat?: 'vasp' | 'qe'
): any {
  if (typeof contentOrTarget === 'string' && targetFormat) {
    return KpointMigration.migrate(contentOrTarget, targetFormat);
  }
  // Called with just context from migrationCommands.ts
  return Promise.resolve();
}
